version: '3.8'
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://host.docker.internal:27017/pcto
    ports:
      - "8080:8080"
    networks:
      - app-network
  mongodb:
    image: mongo:7.0.7
    ports:
      - "27017:27017"
networks:
  app-network:
    driver: bridge


